//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheConfig) DeepCopyInto(out *CacheConfig) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(corev1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConfig.
func (in *CacheConfig) DeepCopy() *CacheConfig {
	if in == nil {
		return nil
	}
	out := new(CacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneConfig) DeepCopyInto(out *CrossplaneConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneConfig.
func (in *CrossplaneConfig) DeepCopy() *CrossplaneConfig {
	if in == nil {
		return nil
	}
	out := new(CrossplaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrossplaneConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneConfigList) DeepCopyInto(out *CrossplaneConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CrossplaneConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneConfigList.
func (in *CrossplaneConfigList) DeepCopy() *CrossplaneConfigList {
	if in == nil {
		return nil
	}
	out := new(CrossplaneConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CrossplaneConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneConfigSpec) DeepCopyInto(out *CrossplaneConfigSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderRef, len(*in))
		copy(*out, *in)
	}
	if in.DefaultActivations != nil {
		in, out := &in.DefaultActivations, &out.DefaultActivations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PackageCache.DeepCopyInto(&out.PackageCache)
	in.FunctionCache.DeepCopyInto(&out.FunctionCache)
	in.Webhooks.DeepCopyInto(&out.Webhooks)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Features.DeepCopyInto(&out.Features)
	in.Registry.DeepCopyInto(&out.Registry)
	in.Observability.DeepCopyInto(&out.Observability)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	if in.ExtraHelmValues != nil {
		in, out := &in.ExtraHelmValues, &out.ExtraHelmValues
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneConfigSpec.
func (in *CrossplaneConfigSpec) DeepCopy() *CrossplaneConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CrossplaneConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneConfigStatus) DeepCopyInto(out *CrossplaneConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneConfigStatus.
func (in *CrossplaneConfigStatus) DeepCopy() *CrossplaneConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CrossplaneConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFlags) DeepCopyInto(out *FeatureFlags) {
	*out = *in
	if in.BetaUsages != nil {
		in, out := &in.BetaUsages, &out.BetaUsages
		*out = new(bool)
		**out = **in
	}
	if in.BetaClaimSSA != nil {
		in, out := &in.BetaClaimSSA, &out.BetaClaimSSA
		*out = new(bool)
		**out = **in
	}
	if in.BetaRealtimeCompositions != nil {
		in, out := &in.BetaRealtimeCompositions, &out.BetaRealtimeCompositions
		*out = new(bool)
		**out = **in
	}
	if in.BetaDeploymentRuntimeConfigs != nil {
		in, out := &in.BetaDeploymentRuntimeConfigs, &out.BetaDeploymentRuntimeConfigs
		*out = new(bool)
		**out = **in
	}
	if in.BetaCustomToManagedResourceConversion != nil {
		in, out := &in.BetaCustomToManagedResourceConversion, &out.BetaCustomToManagedResourceConversion
		*out = new(bool)
		**out = **in
	}
	if in.AlphaOperations != nil {
		in, out := &in.AlphaOperations, &out.AlphaOperations
		*out = new(bool)
		**out = **in
	}
	if in.AlphaDependencyVersionUpgrades != nil {
		in, out := &in.AlphaDependencyVersionUpgrades, &out.AlphaDependencyVersionUpgrades
		*out = new(bool)
		**out = **in
	}
	if in.AlphaDependencyVersionDowngrades != nil {
		in, out := &in.AlphaDependencyVersionDowngrades, &out.AlphaDependencyVersionDowngrades
		*out = new(bool)
		**out = **in
	}
	if in.AlphaSignatureVerification != nil {
		in, out := &in.AlphaSignatureVerification, &out.AlphaSignatureVerification
		*out = new(bool)
		**out = **in
	}
	if in.AlphaFunctionResponseCache != nil {
		in, out := &in.AlphaFunctionResponseCache, &out.AlphaFunctionResponseCache
		*out = new(bool)
		**out = **in
	}
	if in.AlphaPipelineInspector != nil {
		in, out := &in.AlphaPipelineInspector, &out.AlphaPipelineInspector
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFlags.
func (in *FeatureFlags) DeepCopy() *FeatureFlags {
	if in == nil {
		return nil
	}
	out := new(FeatureFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityConfig) DeepCopyInto(out *ObservabilityConfig) {
	*out = *in
	if in.MetricsEnabled != nil {
		in, out := &in.MetricsEnabled, &out.MetricsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DebugEnabled != nil {
		in, out := &in.DebugEnabled, &out.DebugEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityConfig.
func (in *ObservabilityConfig) DeepCopy() *ObservabilityConfig {
	if in == nil {
		return nil
	}
	out := new(ObservabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRef) DeepCopyInto(out *ProviderRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRef.
func (in *ProviderRef) DeepCopy() *ProviderRef {
	if in == nil {
		return nil
	}
	out := new(ProviderRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfig) DeepCopyInto(out *RegistryConfig) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfig.
func (in *RegistryConfig) DeepCopy() *RegistryConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.RBACManager != nil {
		in, out := &in.RBACManager, &out.RBACManager
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountConfig) DeepCopyInto(out *ServiceAccountConfig) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountConfig.
func (in *ServiceAccountConfig) DeepCopy() *ServiceAccountConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
